### ISSUE TITLE
wells_criteria_pulmonary_embolism.v1

### ISSUE THREAD

**Issue by Woooderson** [rongchen/common-clinical-models#1]
This archetype cannot be modeled to sufficient detail. Model requires decimals among Answer options and for the Total score (e.g. 1.5 - Present or 0.5 Total Points).

Ordinal & Count data types only support integer values.
- Solved "Total score" count with Quantity / qualified real data type
- How to calculate the correct value with or without Ordinals / listed objects? We can solve it in GDL such as manually calculating it, e.g. ((gt0001.value) * 1.5), but the archetype will still be wrong itself.

Should we put this archetype + GDL aside from the project?

**Comment by rongchen** [comment]
Essentially the Well's criteria is a check-list and a total score. Each item on the list can be modeled as dv_boolean using the text such as "Heart Rate > 100, 1.5 points". The total score can then be modeled as dv_quantity.

The GDL guideline can do the real calculation with the correct weight points.

This way, we can avoid to use dv_ordinal in the archetype.
