### ISSUE TITLE
Wells_Criteria_DVT_Calculation.v1

### ISSUE THREAD

**Issue by Woooderson** [rongchen/common-clinical-models#2]
This GDL cannot be parsed in GDL Editor. This error appears when trying to parse it:

> Internal error : se.cambio.cds.gdl.model.expression.Variable cannot be cast to se.cambio.cds.gdl.model.expression.AssignmentExpression

I have traced the bug to the ordinal "**Alternative diagnosis to DVT at least as likely**", which contains a answer option with value -2. This is where the GDL breaks.

We need this -2 for the clinical algo, and openEHR ordinals support negative numbers, so this is a GDL problem atm.

**Comment by rongchen** [comment]
It doesn't seem to be related to value -2 if it's a parser issue. I just opened it with the latest editor from 2016/06/11 without any issue. Or have you fixed it already?

**Comment by rongchen** [comment]
If it's indeed the number -2 that caused parsing issue, try to add "(" and ")" around it so the parser can handle it. The issue seems to be related to the GDL code generation from the in-memory models.
